version: '3'

services:
  snort:
    image: easypi/snort-arm
    container_name: snort-docker
    command: -q -c /etc/snort/snort.conf -y -i wlan0
    volumes:
      - ./snort-data:/etc/snort
      - ./snort-data/log:/var/log/snort
    network_mode: host
    restart: unless-stopped
  cowrie:
    image: stingar/cowrie
    container_name: cowrie-docker
    command: start -n
    ports:
      - "2222:2222"
      - "23:2223"
    env_file:
      - ./cowrie-data/env/cowrie.env
    volumes:
      - ./cowrie-data/etc:/etc/cowrie
    network_mode: host
    restart: unless-stopped