version: '3'

services:
  snort:
    image: easypi/snort-arm
    container_name: snort-docker
    command: -q -c /etc/snort/snort.conf -y -i wlan0
    volumes:
      - ./snort-data:/etc/snort
      - ./snort-data/log:/var/log/snort
    network_mode: host
    restart: unless-stopped
  cowrie:
    image: armedpot/cowrie
    container_name: cowrie-docker
    build: ./cowrie-data
    command: sh -c "/home/cowrie/cowrie-git/bin/cowrie start"
    # command: sh -c "find /home/cowrie/cowrie-git/bin -type f -exec sed -i 's/bash/sh/g' {} \;"
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie-data/etc:/home/cowrie/cowrie-git/etc
      - ./cowrie-data/var:/home/cowrie/cowrie-git/var
    network_mode: host
    restart: unless-stopped