version: '3'

services:
  snort:
    image: easypi/snort-arm
    container_name: snort-docker
    command: -q -A console -i wlan0 -c /etc/snort/snort.conf
    volumes:
      - ./snort-data:/etc/snort
      - ./snort-data/log:/var/log/snort
    network_mode: host
    restart: unless-stopped
  cowrie:
    image: armedpot/cowrie
    container_name: cowrie-docker
    build: ./cowrie-data
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie-data/logs:/home/cowrie/cowrie-git/var/log/cowrie
    network_mode: host
    restart: unless-stopped