##Security system based on ubuntu 20.04
FROM ubuntu:20.04

# Adjust Timezone (for correct logging)
RUN echo "Asia/Jakarta" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

# install packages
RUN apt update && \
    apt install -y \
    wget \
    build-essential \

################################### SNORT INSTALLATION ########################################

# Snort pre-requisites
    autotools-dev \
    libdumbnet-dev \
    libluajit-5.1-dev \
    libpcap-dev \

# Snort DAQ (Data AcQuisition library) pre-requisites
    bison \
    flex \

# Optional libraries that improves fuctionality
    zlib1g-dev \
    liblzma-dev \
    openssl \
    libssl-dev \
    cpputest \
    libsqlite3-dev  \

# nghttp libary
    autoconf \
    libtool \
    pkg-config \
    libcmocka-dev \
    libnetfilter-queue-dev \
    libunwind-dev \
    libmnl-dev \
    ethtool \

# barnyard2
    libmysqlclient-dev \
    mysql-client \
    autoconf \
    libtool

# Create snort installation directory
RUN mkdir ~/snort_src

# Install safec for legacy C calls
RUN cd ~/snort_src  \
    && wget https://github.com/rurban/safeclib/releases/download/v02092020/libsafec-02092020.tar.gz    \
    && tar -xzvf libsafec-02092020.tar.gz   \
    && cd libsafec-02092020.0-g6d921f   \
    && ./configure; make; make install


# Below are Hyperscan dependencies for Snort 3 used for fast pattern matching (critical for performance)
## Perl Compatible Regular Expressions
RUN cd ~/snort_src/ \   
    && wget https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.gz  \
    && tar -xzvf pcre-8.45.tar.gz   \
    && cd pcre-8.45 \
    && ./configure; make; make install

## gperf tools 2.9
RUN cd ~/snort_src  \
    && wget https://github.com/gperftools/gperftools/releases/download/gperftools-2.9.1/gperftools-2.9.1.tar.gz \
    && tar xzvf gperftools-2.9.1.tar.gz \
    && cd gperftools-2.9.1  \
    && ./configure; make; make install

## Ragel
RUN cd ~/snort_src  \
    && wget http://www.colm.net/files/ragel/ragel-6.10.tar.gz   \
    && tar -xzvf ragel-6.10.tar.gz  \
    && cd ragel-6.10    \
    && ./configure; make; make install

## Boost C++ library (don't install)
RUN  cd ~/snort_src \   
    && wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz    \
    && tar -xvzf boost_1_76_0.tar.gz

# Install Hyperscan 5.4 from source
RUN cd ~/snort_src  \
    && wget https://github.com/intel/hyperscan/archive/refs/tags/v5.4.0.tar.gz  \
    && tar -xvzf v5.4.0.tar.gz  \
    && mkdir ~/snort_src/hyperscan-5.4.0-build  \
    && cd hyperscan-5.4.0-build/    \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBOOST_ROOT=~/snort_src/boost_1_76_0/ ../hyperscan-5.4.0; make; make install

# Install flatbuffers
RUN cd ~/snort_src  \
    && wget https://github.com/google/flatbuffers/archive/refs/tags/v2.0.0.tar.gz -O flatbuffers-v2.0.0.tar.gz  \
    && tar -xzvf flatbuffers-v2.0.0.tar.gz  \
    && mkdir flatbuffers-build  \
    && cd flatbuffers-build \
    && cmake ../flatbuffers-2.0.0; make; make install


# Install Data Acquisition Library (DAQ)
ENV DAQ_VERSION 3.0.4
RUN cd ~/snort_src  \
    && wget https://github.com/snort3/libdaq/archive/refs/tags/v3.0.4.tar.gz -O libdaq-${DAQ_VERSION}.tar.gz \
    && tar -xzvf libdaq-${DAQ_VERSION}.tar.gz \
    && cd libdaq-${DAQ_VERSION} \
    && ./bootstrap; ./configure; make; make install


# Install Snort-3.1.6.0
ENV SNORT_VERSION 3.1.6.0
RUN wget https://github.com/snort3/snort3/archive/refs/tags/3.1.6.0.tar.gz -O snort3-${SNORT_VERSION}.tar.gz \
    && tar -xzvf snort3-${SNORT_VERSION}.tar.gz \
    && cd snort3-${SNORT_VERSION} \
    && ./configure_cmake.sh --prefix=/usr/local --enable-tcmalloc   \ 
    && cd build \
    && make; make install


# Install barnyard2
RUN wget https://github.com/firnsy/barnyard2/archive/master.tar.gz -O barnyard2-Master.tar.gz \
    && tar zxvf barnyard2-Master.tar.gz \
    && cd barnyard2-master \
    && autoreconf -fvi -I ./m4 \
    && ln -s /usr/include/dumbnet.h /usr/include/dnet.h \
    && ./configure --with-mysql --with-mysql-libraries=/usr/lib/x86_64-linux-gnu; make; make install

# Update shared libaries, or error when starting snort
RUN ldconfig


# Create symlink
#RUN ln -s /usr/local/bin/snort /usr/sbin/snort


# Create Snort directories and files
RUN mkdir -p /etc/snort \
    && mkdir -p /etc/snort/rules \
    && mkdir -p /etc/snort/rules/iplists \
    && mkdir -p /etc/snort/preproc_rules \
    && mkdir -p /usr/local/lib/snort_dynamicrules \
    && mkdir -p /etc/snort/so_rules \

# Create log directories    
&& mkdir -p /var/log/snort \
&& mkdir -p /var/log/snort/archived_logs \

# Create files that stores rules and ip lists
&& touch /etc/snort/rules/iplists/black_list.rules /etc/snort/rules/iplists/white_list.rules /etc/snort/sid-msg.map

# To copy the configuration files and the dynamic preprocessors
RUN cp /snort-${SNORT_VERSION}/etc/*.map /etc/snort \
&& cp snort-${SNORT_VERSION}/etc/*.conf* /etc/snort \
&& cp /snort-${SNORT_VERSION}/etc/*.dtd /etc/snort \
&& cp /snort-${SNORT_VERSION}/src/dynamic-preprocessors/build/usr/local/lib/snort_dynamicpreprocessor/* /usr/local/lib/snort_dynamicpreprocessor/



ADD /templates/snort.conf /etc/snort/
ADD /templates/sid-msg.map /etc/snort/
ADD /templates/rules/snort.rules /etc/snort/rules/
ADD /templates/rules/iplists/* /etc/snort/rules/iplists/

# Create Barnyard2 directories and files
RUN cd barnyard2-master \

&& cp etc/barnyard2.conf /etc/snort/ \
&& mkdir /var/log/barnyard2 \
&& touch /var/log/snort/barnyard2.waldo