version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant
    volumes:
      - ./homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
  esphome:
    container_name: esphome
    image: esphome/esphome
    privileged: true
    ports:
      - 6052:6052
      - 5533:53
    volumes:
      - ./esphome-config:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    restart: always